<!DOCTYPE html>
<html lang="fr">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>Reset Password - MyWishList</title>
    <style>
        a:hover {
            text-decoration: underline !important;
        }
    </style>
</head>
<body style="margin: auto; height: 100vh; display: flex; background-color: #f2f3f8;">
    <table style="font-family: 'Open Sans', sans-serif;background-color:#f2f3f8;display:flex;margin:auto;justify-content:center;">
        <tr>
            <td>
                <table style="background-color: #f2f3f8; max-width:670px;  margin:0 auto;">
                    <tr>
                        <td style="text-align:center;">
                            <img width="60" src="https://share.garnx.fr/8dwu" title="logo" alt="logo">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table style="margin:auto; padding: 3vh; max-width:670px;background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                                <tr>
                                    <td style="height:40px;">&nbsp;</td>
                                </tr>
                                <tr>
                                    <td style="padding:0 35px;">
                                        <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">{TITLE}</h1>
                                        <span style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;"></span>
                                        <p style="color:#455056; font-size:15px;line-height:24px; margin:0;"> {MESSAGE} </p>
                                        <a href="{LINK}" style="background:#20e277;text-decoration:none !important; font-weight:500; margin-top:35px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Reset Password</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding-top:4vh;">
                                        <p style="color:#455056; font-size:10px; margin:0;"> {MESSAGE_ALT} </p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>