    <div class="main-content">
        <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
            <div class="container-fluid">
                <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="%main_route%"><img alt="logo" class="icon" src="/assets/img/logos/6.png"/>MyWishList</a>
                <a class="nav-link pr-0" href="%main_route%" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm"><img class="rounded-circle" alt="avatar" src="%avatar_src%"></span>
                        <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">%user_lastname% %user_firstname%</span>
                        </div>
                    </div>
                </a>
            </div>
        </nav>
        <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 300px;  background-size: cover; background-position: center top;">
            <span class="mask bg-gradient-default opacity-8"></span>
            <div class="container-fluid align-items-center">
                <div class="row">
                    <div class="col-lg-7 col-md-10">
                        <h1 class="display-2 text-white">{#hello#} %user_firstname%</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
                    <div class="row-2">
                        <form method="post" class="fw" id="upload_form" enctype="multipart/form-data" action="%profile_route%">
                            <div class="card card-profile shadow">
                                <div class="row justify-content-center">
                                    <div class="col-lg-3 order-lg-2">
                                        <div class="card-profile-image">
                                            <img src="%avatar_src%" alt="avatar" class="rounded-circle">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                                    <div class="d-flex justify-content-between">
                                        <button type="button" id="upload_btn" class="btn btn-sm btn-info mr-4">{#upload#}</button>
                                        <input type="file" accept="image/*" name="avatarinput" id="avatar-upload" class="invisible"/>
                                        <button type="submit" id="delete_btn" name="delete_btn" value="delete" class="btn btn-sm btn-danger float-right">{#delete#}</button>
                                    </div>
                                </div>
                                <div class="card-body pt-0 pt-md-4">%info_msg%
                                    <div class="text-center">
                                        <h3>%user_lastname% %user_firstname%</h3>
                                        <p class="userinfo">{#creation_date#} %user_created_at%</p>
                                        <p class="userinfo">{#last_update#} %user_updated_at%</p>
                                        <p class="userinfo">{#last_login#} %user_lastlogged_at% [%user_lastlogged_ip%]</p>
                                        <p class="userinfo">{#api_key#} : %user_api_key%</p>
                                    </div>
                                    <a href="%api_key_route%" class="btn btn-sm btn-primary">{#regenerate#}</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="row-2 row-3">
                        <div class="card card-profile shadow fw">
                            <h3 class="text-center pt-2">{#phtml_my_lists#}</h3>
                            <div class="lists">
                                %mylists%
                            </div>
                        </div>
                    </div>
                </div>
                <!--VueListe ici -->
                <div class="col-xl-8 order-xl-1">
                    <form onsubmit="return matchPwd()" method="post" action="%profile_route%">
                        <div class="card bg-secondary shadow">
                            <div class="card-header bg-white border-0">
                                <div class="row align-items-center">
                                    <div class="col-8">
                                        <h3 class="mb-0">{#my_infos_title#}</h3>
                                    </div>
                                    <div class="col-4 text-right">
                                        <a href="%logout_route%" class="btn btn-sm btn-danger btn-danger-fr">{#logout#}</a>
                                        <button type="submit" class="btn btn-sm btn-primary">{#update#}</button>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <h6 class="heading-small text-muted mb-4">{#user#}</h6>
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-username">{#user_username#}</label>
                                                <input type="text" id="input-username" autocomplete="off" name="input-username" disabled class="form-control form-control-alternative" placeholder="{#user_username#}" value="%user_username%">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label class="form-control-label" for="input-email">{#user_email#}</label>
                                                <input type="email" id="input-email" autocomplete="email" name="input-email" class="form-control form-control-alternative" value="%user_email%">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-last-name">{#user_lastname#}</label>
                                                <input type="text" id="input-last-name" autocomplete="family-name" name="input-last-name" class="form-control form-control-alternative" placeholder="{#user_lastname#}" value="%user_lastname%">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-first-name">{#user_firstname#}</label>
                                                <input type="text" id="input-first-name" name="input-first-name" autocomplete="given-name" class="form-control form-control-alternative" placeholder="{#user_firstname#}" value="%user_firstname%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr class="my-4">
                                <h6 class="heading-small text-muted mb-4">{#user_password#}</h6>
                                <div class="pl-lg-4">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-old-password">{#user_old_password#}</label>
                                                <div class='pfield'><input type="password" id="input-old-password" name="input-old-password" autocomplete="current-password" class="form-control form-control-alternative" required placeholder="{#required#}"><i data-associated="input-old-password" class="pwdicon far fa-eye"></i></div>
                                            </div>
                                            <div>
                                                <a href="%2fa_route%" class="btn btn-sm btn-default">{#user_2fa_code#}</a>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-new-password">{#user_new_password#}</label>
                                                <div class="pfield"><input type="password" id="input-new-password" minlength="14" maxlength="40" pattern="(?=.*\d)(?=.*[a-z])(?=.*[~!@#$%^&*()\-_=+[\]{};:,<>\/?|])(?=.*[A-Z]).{14,}" name="input-new-password" autocomplete="new-password" class="form-control form-control-alternative"><i data-associated="input-new-password" class="pwdicon far fa-eye"></i></div>
                                            </div>
                                            <div id="message">
                                                <h6 class="heading-small text-muted mb-4">{#password_form_valid#}</h6>
                                                <p id="small" class="invalid">{#password_form_valid_small#}</p>
                                                <p id="capital" class="invalid">{#password_form_valid_capital#}</p>
                                                <p id="number" class="invalid">{#password_form_valid_number#}</p>
                                                <p id="special" class="invalid">{#password_form_valid_special#}</p>
                                                <p id="length" class="invalid">{#password_form_valid_length#}</p>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group focused">
                                                <label class="form-control-label" for="input-new-password-c">{#user_password_confirm#}</label>
                                                <div class="pfield"><input type="password" id="input-new-password-c" minlength="14" maxlength="40" pattern="(?=.*\d)(?=.*[a-z])(?=.*[~!@#$%^&*()\-_=+[\]{};:,<>\/?|])(?=.*[A-Z]).{14,}" autocomplete="new-password" name="input-new-password-c" class="form-control form-control-alternative"><i data-associated="input-new-password-c" class="pwdicon far fa-eye"></i></div>
                                            </div>
                                            <div class='float-right'>
                                                <a href="%delete_account_route%" class="btn btn-sm btn-danger">{#user_delete_account#}</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/js/password-validator.js"></script>
    <script src="/assets/js/password-viewer.js"></script>
    <script src="/assets/js/avatar-upload.js"></script>
</body>
</html>