    <div class="sidebar">
        <div class="logo-details">
            <i class='bx bx-list-check icon'></i>
            <div class="logo_name">MyWishList</div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nav-list">
            <li>
                <a href="/">
                    <i class='bx bx-home-alt'></i>
                    <span class="links_name">{#home_title#}</span>
                </a>
                <span class="tooltip">{#home_title#}</span>
            </li>
            <li>
                <a href="%my_lists_route%">
                    <i class='bx bx-list-ul'></i>
                    <span class="links_name">{#phtml_public_lists#}</span>
                </a>
                <span class="tooltip">{#phtml_public_lists#}</span>
            </li>
            <li>
                <a href="%createurs_route%">
                    <i class='bx bxs-user-detail'></i>
                    <span class="links_name">{#phtml_creators#}</span>
                </a>
                <span class="tooltip">{#phtml_creators#}</span>
            </li>
            <li>
                <a href="%create_list_route%">
                    <i class='bx bx-list-plus'></i>
                    <span class="links_name">{#phtml_lists_create#}</span>
                </a>
                <span class="tooltip">{#phtml_lists_create#}</span>
            </li>
            %userprofile%
            <li class="lang">
                <div class="lang-menu">
                    <div class="selected-lang">%flag_img%</div>
                    <span class="links_name">{#__#}</span>
                    <ul>
                        <li><a href="?lang=fr" class="fr"><img alt="fr-flag" src="/assets/img/flags/flag-fr.png">FR</a></li>
                        <li><a href="?lang=en" class="en"><img alt="uk-flag" src="/assets/img/flags/flag-en.png">EN</a></li>
                    </ul>
                </div>
            </li>
            <li class="profile">
                <div class="profile-details">
                    <span>%user_name%</span>
                </div>
                <a class='tobtn' href="%href%"><i class="%iconclass%" id="logbtn"></i> </a>
            </li>
        </ul>
    </div>
    <script>
        let sidebar = document.querySelector(".sidebar");
        let closeBtn = document.querySelector("#btn");
        closeBtn.addEventListener("click", () => {
            sidebar.classList.toggle("open");
            menuBtnChange();
        });
        let menuBtnChange = () => {
            if (sidebar.classList.contains("open"))
                closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");
            else
                closeBtn.classList.replace("bx-menu-alt-right", "bx-menu");
        }
    </script>
