Search.appendIndex(
    [
                {
            "fqsen": "\\mywishlist\\db\\Eloquent",
            "name": "Eloquent",
            "summary": "Eloquent\u0020Database\u0020Manager\u0020Class",
            "url": "classes/mywishlist-db-Eloquent.html"
        },                {
            "fqsen": "\\mywishlist\\db\\Eloquent\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Static\u0020method\u0020to\u0020connect\u0020to\u0020the\u0020database",
            "url": "classes/mywishlist-db-Eloquent.html#method_start"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey",
            "name": "HasCompositePrimaryKey",
            "summary": "Generic\u0020class\u0020for\u0020all\u0020the\u0020classes\u0020that\u0020have\u0020a\u0020composite\u0020primary\u0020key\nSource\u0020\u003A\u0020https\u003A\/\/github.com\/mopo922\/LaravelTreats\/blob\/master\/src\/Model\/Traits\/HasCompositePrimaryKey.php",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003AgetIncrementing\u0028\u0029",
            "name": "getIncrementing",
            "summary": "Get\u0020the\u0020value\u0020indicating\u0020whether\u0020the\u0020IDs\u0020are\u0020incrementing.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_getIncrementing"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003AgetKey\u0028\u0029",
            "name": "getKey",
            "summary": "Get\u0020the\u0020value\u0020of\u0020the\u0020model\u0027s\u0020primary\u0020key.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_getKey"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003AsetKeysForSaveQuery\u0028\u0029",
            "name": "setKeysForSaveQuery",
            "summary": "Set\u0020the\u0020keys\u0020for\u0020a\u0020save\u0020update\u0020query.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_setKeysForSaveQuery"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Execute\u0020a\u0020query\u0020for\u0020a\u0020single\u0020record\u0020by\u0020ID.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_find"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003AfindOrFail\u0028\u0029",
            "name": "findOrFail",
            "summary": "Find\u0020a\u0020model\u0020by\u0020its\u0020primary\u0020key\u0020or\u0020throw\u0020an\u0020exception.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_findOrFail"
        },                {
            "fqsen": "\\mywishlist\\db\\HasCompositePrimaryKey\u003A\u003Arefresh\u0028\u0029",
            "name": "refresh",
            "summary": "Reload\u0020the\u0020current\u0020model\u0020instance\u0020with\u0020fresh\u0020attributes\u0020from\u0020the\u0020database.",
            "url": "classes/mywishlist-db-HasCompositePrimaryKey.html#method_refresh"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ExceptionHandler",
            "name": "ExceptionHandler",
            "summary": "Class\u0020ExceptionHandler\nHandle\u0020exceptions\u0020from\u0020Slim\u0020framework",
            "url": "classes/mywishlist-exceptions-ExceptionHandler.html"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ExceptionHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ExceptionHandler\u0020constructor",
            "url": "classes/mywishlist-exceptions-ExceptionHandler.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ExceptionHandler\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Handle\u0020exceptions",
            "url": "classes/mywishlist-exceptions-ExceptionHandler.html#method___invoke"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ExceptionHandler\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "",
            "url": "classes/mywishlist-exceptions-ExceptionHandler.html#property_lang"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ExceptionHandler\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-exceptions-ExceptionHandler.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ForbiddenException",
            "name": "ForbiddenException",
            "summary": "Class\u0020ForbiddenException\nInherits\u0020from\u0020Exception\nGenerated\u0020when\u0020a\u0020forbidden\u0020action\u0020is\u0020attempted",
            "url": "classes/mywishlist-exceptions-ForbiddenException.html"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ForbiddenException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ForbiddenException\u0020constructor",
            "url": "classes/mywishlist-exceptions-ForbiddenException.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ForbiddenException\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Get\u0020the\u0020title\u0020of\u0020the\u0020exception",
            "url": "classes/mywishlist-exceptions-ForbiddenException.html#method_getTitle"
        },                {
            "fqsen": "\\mywishlist\\exceptions\\ForbiddenException\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/mywishlist-exceptions-ForbiddenException.html#property_title"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper",
            "name": "ImgCropper",
            "summary": "Image\u0020Cropper\u0020Class\nUtils\u0020to\u0020circle\u0020crop\u0020an\u0020image",
            "url": "classes/mywishlist-ImgCropper.html"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/mywishlist-ImgCropper.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Save\u0020image\u0020to\u0020disk",
            "url": "classes/mywishlist-ImgCropper.html#method_save"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper\u003A\u003A\u0024image",
            "name": "image",
            "summary": "",
            "url": "classes/mywishlist-ImgCropper.html#property_image"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper\u003A\u003A\u0024finfo",
            "name": "finfo",
            "summary": "",
            "url": "classes/mywishlist-ImgCropper.html#property_finfo"
        },                {
            "fqsen": "\\mywishlist\\ImgCropper\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-ImgCropper.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\MailSender",
            "name": "MailSender",
            "summary": "Class\u0020Mail\u0020Sender\nUsage\u0020of\u0020PHPMailer",
            "url": "classes/mywishlist-MailSender.html"
        },                {
            "fqsen": "\\mywishlist\\MailSender\u003A\u003AsendMail\u0028\u0029",
            "name": "sendMail",
            "summary": "Send\u0020an\u0020email",
            "url": "classes/mywishlist-MailSender.html#method_sendMail"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI",
            "name": "ControllerAPI",
            "summary": "Class\u0020ControllerAPI\nController\u0020for\u0020the\u0020global\u0020API",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ControllerAPI\u0020constructor",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003AitemsV1\u0028\u0029",
            "name": "itemsV1",
            "summary": "Generate\u0020JSON\u0020response\u0020for\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method_itemsV1"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003AlistsV1\u0028\u0029",
            "name": "listsV1",
            "summary": "Generate\u0020JSON\u0020response\u0020with\u0020a\u0020list\u0020of\u0020items",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method_listsV1"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003Aunauthorized\u0028\u0029",
            "name": "unauthorized",
            "summary": "Send\u0020a\u0020401\u0020Unauthorized\u0020response",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method_unauthorized"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003AnotAllowed\u0028\u0029",
            "name": "notAllowed",
            "summary": "Send\u0020a\u0020405\u0020Method\u0020Not\u0020Allowed\u0020response",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method_notAllowed"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003Aforbidden\u0028\u0029",
            "name": "forbidden",
            "summary": "Send\u0020a\u0020403\u0020Forbidden\u0020response",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#method_forbidden"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#property_user"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#property_request"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#property_response"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerAPI\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerAPI.html#property_args"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem",
            "name": "ControllerItem",
            "summary": "Class\u0020ControllerItem\nController\u0020for\u0020Item\u0020Model",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ControllerItem\u0020constructor",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Control\u0020edition\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003AcreatePot\u0028\u0029",
            "name": "createPot",
            "summary": "Control\u0020creation\u0020of\u0020pot\u0020for\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_createPot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003AdeletePot\u0028\u0029",
            "name": "deletePot",
            "summary": "Control\u0020creation\u0020of\u0020pot\u0020for\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_deletePot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003AparticipatePot\u0028\u0029",
            "name": "participatePot",
            "summary": "Control\u0020editing\u0020of\u0020pot\u0020for\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_participatePot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003Areserve\u0028\u0029",
            "name": "reserve",
            "summary": "Control\u0020reservation\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_reserve"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Control\u0020the\u0020deletion\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_delete"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Control\u0020the\u0020display\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003AactionPot\u0028\u0029",
            "name": "actionPot",
            "summary": "Process\u0020request\u0020for\u0020the\u0020pot\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#method_actionPot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_user"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024item",
            "name": "item",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_item"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024renderer",
            "name": "renderer",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_renderer"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_request"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_response"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerItem\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerItem.html#property_args"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList",
            "name": "ControllerList",
            "summary": "Class\u0020ControllerList\nController\u0020for\u0020Liste\u0020Model",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ControllerList\u0020constructor",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Control\u0020edition\u0020of\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003AaddMessage\u0028\u0029",
            "name": "addMessage",
            "summary": "Control\u0020adding\u0020message\u0020to\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_addMessage"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003AaddItem\u0028\u0029",
            "name": "addItem",
            "summary": "Control\u0020adding\u0020an\u0020item\u0020to\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_addItem"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Control\u0020deletion\u0020of\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_delete"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Control\u0020creation\u0020of\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_create"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003Aclaim\u0028\u0029",
            "name": "claim",
            "summary": "Control\u0020claim\u0020of\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_claim"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Control\u0020display\u0020of\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_user"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024liste",
            "name": "liste",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_liste"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024renderer",
            "name": "renderer",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_renderer"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_request"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerList\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerList.html#property_response"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser",
            "name": "ControllerUser",
            "summary": "Class\u0020ControllerUser\nController\u0020for\u0020User\u0020Model",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ControllerUser\u0020constructor",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Aprofile\u0028\u0029",
            "name": "profile",
            "summary": "Control\u0020the\u0020display\u0020of\u0020the\u0020user\u0027s\u0020profile",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_profile"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003AcreateApiKey\u0028\u0029",
            "name": "createApiKey",
            "summary": "Control\u0020the\u0020user\u0020api\u0020key\u0020generation",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_createApiKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Control\u0020the\u0020login\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_login"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Ahome\u0028\u0029",
            "name": "home",
            "summary": "Control\u0020the\u0020home\u0020page\u0020render",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_home"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Acreators\u0028\u0029",
            "name": "creators",
            "summary": "Control\u0020the\u0020creators\u0020page\u0020render",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_creators"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003ApublicLists\u0028\u0029",
            "name": "publicLists",
            "summary": "Control\u0020the\u0020public\u0020lists\u0020page\u0020render",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_publicLists"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Control\u0020the\u0020register\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_register"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Control\u0020the\u0020logout\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_logout"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003AdeleteAvatar\u0028\u0029",
            "name": "deleteAvatar",
            "summary": "Control\u0020delete\u0020avatar\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_deleteAvatar"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Aauth2FA\u0028\u0029",
            "name": "auth2FA",
            "summary": "Control\u0020the\u00202FA\u0020login\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_auth2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Areset_password\u0028\u0029",
            "name": "reset_password",
            "summary": "Control\u0020the\u0020reset\u0020password\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_reset_password"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Control\u0020delete\u0020account\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_delete"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Aforgot_password\u0028\u0029",
            "name": "forgot_password",
            "summary": "Control\u0020the\u0020forgot\u0020password\u0020action",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_forgot_password"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Process\u0020request\u0020for\u0020the\u0020user\u0020model",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#method_process"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_user"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024renderer",
            "name": "renderer",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_renderer"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_request"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_response"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers\\ControllerUser\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/mywishlist-mvc-controllers-ControllerUser.html#property_args"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte",
            "name": "Cagnotte",
            "summary": "Cagnotte\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003Aitem\u0028\u0029",
            "name": "item",
            "summary": "Get\u0020the\u0020associated\u0020item\u0020of\u0020a\u0020pot",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_item"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003AisExpired\u0028\u0029",
            "name": "isExpired",
            "summary": "Check\u0020if\u0020a\u0020pot\u0020is\u0020expired",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_isExpired"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003Aparticipants\u0028\u0029",
            "name": "participants",
            "summary": "Get\u0020all\u0020participants\u0020of\u0020a\u0020pot",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_participants"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003AtotalAmount\u0028\u0029",
            "name": "totalAmount",
            "summary": "Get\u0020total\u0020amount\u0020of\u0020a\u0020pot",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_totalAmount"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003Areste\u0028\u0029",
            "name": "reste",
            "summary": "Calculate\u0020the\u0020remaining\u0020amount\u0020of\u0020a\u0020pot",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_reste"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Delete\u0020a\u0020pot\nDelete\u0020all\u0020participations\u0020of\u0020the\u0020pot",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#method_remove"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Cagnotte\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Cagnotte.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item",
            "name": "Item",
            "summary": "Item\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Item.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003Aliste\u0028\u0029",
            "name": "liste",
            "summary": "Get\u0020the\u0020associated\u0020list\u0020of\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-models-Item.html#method_liste"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003AgetReservationState\u0028\u0029",
            "name": "getReservationState",
            "summary": "Internal\u0020method\u0020for\u0020toJSON\u0028\u0029\u0020method\u0020of\u0020Slim",
            "url": "classes/mywishlist-mvc-models-Item.html#method_getReservationState"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Item.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Item.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Item.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Item.html#property_hidden"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Item\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Item.html#property_fillable"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste",
            "name": "Liste",
            "summary": "Liste\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Liste.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003Aitems\u0028\u0029",
            "name": "items",
            "summary": "Get\u0020items\u0020associated\u0020to\u0020the\u0020list",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_items"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003AisExpired\u0028\u0029",
            "name": "isExpired",
            "summary": "Check\u0020if\u0020a\u0020list\u0020is\u0020expired",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_isExpired"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003AisPublished\u0028\u0029",
            "name": "isPublished",
            "summary": "Check\u0020if\u0020a\u0020list\u0020is\u0020published",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_isPublished"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003AisPublic\u0028\u0029",
            "name": "isPublic",
            "summary": "Check\u0020if\u0020a\u0020list\u0020is\u0020public",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_isPublic"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003AgetUserNameAttribute\u0028\u0029",
            "name": "getUserNameAttribute",
            "summary": "Internal\u0020method\u0020for\u0020toJSON\u0028\u0029\u0020method\u0020of\u0020Slim",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_getUserNameAttribute"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003AisClaimed\u0028\u0029",
            "name": "isClaimed",
            "summary": "Check\u0020if\u0020a\u0020list\u0020is\u0020claimed",
            "url": "classes/mywishlist-mvc-models-Liste.html#method_isClaimed"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_hidden"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024appends",
            "name": "appends",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_appends"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Liste\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Liste.html#property_fillable"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message",
            "name": "Message",
            "summary": "Message\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Message.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Get\u0020the\u0020user\u0020that\u0020reserved\u0020the\u0020item",
            "url": "classes/mywishlist-mvc-models-Message.html#method_getUser"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Message.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Message.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Message.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Message.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Message\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Message.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation",
            "name": "Participation",
            "summary": "Participation\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Participation.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024keyType",
            "name": "keyType",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_keyType"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Participation\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Participation.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset",
            "name": "PasswordReset",
            "summary": "Password\u0020Reset\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003Aexpired\u0028\u0029",
            "name": "expired",
            "summary": "Check\u0020if\u0020a\u0020list\u0020is\u0020expired",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#method_expired"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024keyType",
            "name": "keyType",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_keyType"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\PasswordReset\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-PasswordReset.html#property_fillable"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode",
            "name": "RescueCode",
            "summary": "RescueCode\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-RescueCode.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024keyType",
            "name": "keyType",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_keyType"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\RescueCode\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-RescueCode.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation",
            "name": "Reservation",
            "summary": "Reservation\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-Reservation.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Get\u0020the\u0020user\u0020that\u0020reserved\u0020the\u0020item",
            "url": "classes/mywishlist-mvc-models-Reservation.html#method_getUser"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Reservation.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Reservation.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Reservation.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Reservation.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\Reservation\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-Reservation.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User",
            "name": "User",
            "summary": "User\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-User.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\nForce\u0020the\u0020user_id\u0020to\u0020\u002D1",
            "url": "classes/mywishlist-mvc-models-User.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logout\u0020the\u0020user",
            "url": "classes/mywishlist-mvc-models-User.html#method_logout"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003Acreate2FA\u0028\u0029",
            "name": "create2FA",
            "summary": "Associate\u00202FA\u0020with\u0020the\u0020user",
            "url": "classes/mywishlist-mvc-models-User.html#method_create2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003Aremove2FA\u0028\u0029",
            "name": "remove2FA",
            "summary": "Disassociate\u00202FA\u0020of\u0020the\u0020user",
            "url": "classes/mywishlist-mvc-models-User.html#method_remove2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "Check\u0020if\u0020the\u0020user\u0020is\u0020an\u0020adminisrator",
            "url": "classes/mywishlist-mvc-models-User.html#method_isAdmin"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "Return\u0020the\u0020user\u0027s\u0020firstname\u0020and\u0020lastname",
            "url": "classes/mywishlist-mvc-models-User.html#method_name"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003AcanInteractWithList\u0028\u0029",
            "name": "canInteractWithList",
            "summary": "Check\u0020if\u0020the\u0020user\u0020can\u0020interact\u0020with\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-models-User.html#method_canInteractWithList"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Authenticate\u0020the\u0020user\nFill\u0020the\u0020\u0024_SESSION\u0020array\u0020and\u0020update\u0020some\u0020vars\u0020from\u0020the\u0020database",
            "url": "classes/mywishlist-mvc-models-User.html#method_authenticate"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-User.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-User.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-User.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\User\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-User.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver",
            "name": "UserTemporaryResolver",
            "summary": "UserTemp\u0020Model\nInherits\u0020from\u0020the\u0020Model\u0020class\u0020of\u0020Laravel",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003Aliste\u0028\u0029",
            "name": "liste",
            "summary": "Get\u0020the\u0020associated\u0020list\u0020of\u0020a\u0020tmp\u0020resolver",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#method_liste"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#property_table"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#property_primaryKey"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003A\u0024incrementing",
            "name": "incrementing",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#property_incrementing"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#property_timestamps"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models\\UserTemporaryResolver\u003A\u003A\u0024guarded",
            "name": "guarded",
            "summary": "",
            "url": "classes/mywishlist-mvc-models-UserTemporaryResolver.html#property_guarded"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer",
            "name": "Renderer",
            "summary": "Class\u0020Renderer\nAbstract\u0020class\u0020for\u0020rendering\u0020views\u0020with\u0020constants",
            "url": "classes/mywishlist-mvc-Renderer.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ASHOW",
            "name": "SHOW",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_SHOW"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ASHOW_FOR_ITEM",
            "name": "SHOW_FOR_ITEM",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_SHOW_FOR_ITEM"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ASHOW_FOR_MENU",
            "name": "SHOW_FOR_MENU",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_SHOW_FOR_MENU"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ACREATE",
            "name": "CREATE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_CREATE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AEDIT",
            "name": "EDIT",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_EDIT"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AHOME_HOME",
            "name": "HOME_HOME",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_HOME_HOME"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AHOME_LISTS",
            "name": "HOME_LISTS",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_HOME_LISTS"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AHOME_CREATORS",
            "name": "HOME_CREATORS",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_HOME_CREATORS"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AEDIT_ADD_ITEM",
            "name": "EDIT_ADD_ITEM",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_EDIT_ADD_ITEM"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003APOT_CREATE",
            "name": "POT_CREATE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_POT_CREATE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003APOT_PARTICIPATE",
            "name": "POT_PARTICIPATE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_POT_PARTICIPATE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ARESERVATION_FORM",
            "name": "RESERVATION_FORM",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_RESERVATION_FORM"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AREQUEST_AUTH",
            "name": "REQUEST_AUTH",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_REQUEST_AUTH"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ALOGIN",
            "name": "LOGIN",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_LOGIN"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ALOGIN_2FA",
            "name": "LOGIN_2FA",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_LOGIN_2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AREGISTER",
            "name": "REGISTER",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_REGISTER"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AENABLE_2FA",
            "name": "ENABLE_2FA",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_ENABLE_2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AMANAGE_2FA",
            "name": "MANAGE_2FA",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_MANAGE_2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ASHOW_2FA_CODES",
            "name": "SHOW_2FA_CODES",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_SHOW_2FA_CODES"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ARECOVER_2FA",
            "name": "RECOVER_2FA",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_RECOVER_2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ALOST_PASSWORD",
            "name": "LOST_PASSWORD",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_LOST_PASSWORD"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ARESET_PASSWORD",
            "name": "RESET_PASSWORD",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_RESET_PASSWORD"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003ADELETE_ACCOUNT_CONFIRM",
            "name": "DELETE_ACCOUNT_CONFIRM",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_DELETE_ACCOUNT_CONFIRM"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AOTHER_MODE",
            "name": "OTHER_MODE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_OTHER_MODE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AOWNER_MODE",
            "name": "OWNER_MODE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_OWNER_MODE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\Renderer\u003A\u003AADMIN_MODE",
            "name": "ADMIN_MODE",
            "summary": "",
            "url": "classes/mywishlist-mvc-Renderer.html#constant_ADMIN_MODE"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View",
            "name": "View",
            "summary": "Abstract\u0020class\u0020View\nInstanciate\u0020a\u0020view",
            "url": "classes/mywishlist-mvc-View.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "View\u0020constructor",
            "url": "classes/mywishlist-mvc-View.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/mywishlist-mvc-View.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/mywishlist-mvc-View.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003ArequestAuth\u0028\u0029",
            "name": "requestAuth",
            "summary": "Display\u0020the\u0020general\u0020auth\u0020page",
            "url": "classes/mywishlist-mvc-View.html#method_requestAuth"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020page",
            "url": "classes/mywishlist-mvc-View.html#method_render"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "JSON\u0020Encoding\u0020method",
            "url": "classes/mywishlist-mvc-View.html#method_encode"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/mywishlist-mvc-View.html#property_request"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/mywishlist-mvc-View.html#property_container"
        },                {
            "fqsen": "\\mywishlist\\mvc\\View\u003A\u003A\u0024access_level",
            "name": "access_level",
            "summary": "",
            "url": "classes/mywishlist-mvc-View.html#property_access_level"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView",
            "name": "ItemView",
            "summary": "Item\u0020View\nInherits\u0020from\u0020View",
            "url": "classes/mywishlist-mvc-views-ItemView.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003AcreatePot\u0028\u0029",
            "name": "createPot",
            "summary": "Display\u0020pot\u0020creation\u0020page",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_createPot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003AparticipatePot\u0028\u0029",
            "name": "participatePot",
            "summary": "Display\u0020pot\u0020participation\u0020page",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_participatePot"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003Areserve\u0028\u0029",
            "name": "reserve",
            "summary": "Display\u0020item\u0020reservation\u0020form",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_reserve"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Display\u0020edit\u0020item\u0020page",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020page",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_render"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "JSON\u0020Encoding\u0020method",
            "url": "classes/mywishlist-mvc-views-ItemView.html#method_encode"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ItemView\u003A\u003A\u0024item",
            "name": "item",
            "summary": "",
            "url": "classes/mywishlist-mvc-views-ItemView.html#property_item"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView",
            "name": "ListView",
            "summary": "List\u0020View\nInherits\u0020from\u0020View",
            "url": "classes/mywishlist-mvc-views-ListView.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ListView\u0020constructor",
            "url": "classes/mywishlist-mvc-views-ListView.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020list",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003AcreateList\u0028\u0029",
            "name": "createList",
            "summary": "Display\u0020list\u0020creation\u0020page",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_createList"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003AaddItem\u0028\u0029",
            "name": "addItem",
            "summary": "Display\u0020add\u0020an\u0020item\u0020to\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_addItem"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Display\u0020list\u0020edition",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003AshowForItem\u0028\u0029",
            "name": "showForItem",
            "summary": "Display\u0020the\u0020list\u0020for\u0020an\u0020item",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_showForItem"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003AshowForMenu\u0028\u0029",
            "name": "showForMenu",
            "summary": "Display\u0020the\u0020list\u0020for\u0020public\u0020lists",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_showForMenu"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020page",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_render"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "JSON\u0020Encoding\u0020method",
            "url": "classes/mywishlist-mvc-views-ListView.html#method_encode"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\ListView\u003A\u003A\u0024list",
            "name": "list",
            "summary": "",
            "url": "classes/mywishlist-mvc-views-ListView.html#property_list"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView",
            "name": "UserView",
            "summary": "User\u0020View",
            "url": "classes/mywishlist-mvc-views-UserView.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UserView\u0020constructor",
            "url": "classes/mywishlist-mvc-views-UserView.html#method___construct"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Display\u0020login\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_login"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AforgotPassword\u0028\u0029",
            "name": "forgotPassword",
            "summary": "Display\u0020forgot\u0020password\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_forgotPassword"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "Display\u0020reset\u0020password\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_resetPassword"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Arecover2FA\u0028\u0029",
            "name": "recover2FA",
            "summary": "Display\u0020the\u00202fa\u0020recover\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_recover2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Display\u0020the\u0020register\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_register"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020profile\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_show"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Aenable2FA\u0028\u0029",
            "name": "enable2FA",
            "summary": "Display\u0020the\u00202fa\u0020enabling\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_enable2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AdeleteAccount\u0028\u0029",
            "name": "deleteAccount",
            "summary": "Display\u0020the\u00202fa\u0020enabling\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_deleteAccount"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Amanage2FA\u0028\u0029",
            "name": "manage2FA",
            "summary": "Display\u0020the\u00202fa\u0020manage\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_manage2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Ashow2FACodes\u0028\u0029",
            "name": "show2FACodes",
            "summary": "Display\u0020the\u00202fa\u0020rescue\u0020codes\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_show2FACodes"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AshowHome\u0028\u0029",
            "name": "showHome",
            "summary": "Display\u0020the\u0020home\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_showHome"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AshowCreators\u0028\u0029",
            "name": "showCreators",
            "summary": "Display\u0020the\u0020creators\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_showCreators"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AshowPublicLists\u0028\u0029",
            "name": "showPublicLists",
            "summary": "Display\u0020the\u0020public\u0020lists\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_showPublicLists"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Asidebar\u0028\u0029",
            "name": "sidebar",
            "summary": "Display\u0020the\u0020sidebar",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_sidebar"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AshowInList\u0028\u0029",
            "name": "showInList",
            "summary": "Display\u0020the\u0020profile\u0020of\u0020user\u0020for\u0020include\u0020in\u0020a\u0020list",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_showInList"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020page",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_render"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Awith2FA\u0028\u0029",
            "name": "with2FA",
            "summary": "Add\u00202fa\u0020key\u0020to\u0020view",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_with2FA"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003AgetHeaderInfo\u0028\u0029",
            "name": "getHeaderInfo",
            "summary": "Get\u0020the\u0020info\u0020parameter\u0020in\u0020the\u0020request",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_getHeaderInfo"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "JSON\u0020Encoding\u0020method",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_encode"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "\u005BNEXISTS\u005D\u0020Edit\u0020user\u0020function",
            "url": "classes/mywishlist-mvc-views-UserView.html#method_edit"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/mywishlist-mvc-views-UserView.html#property_user"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views\\UserView\u003A\u003A\u0024secret",
            "name": "secret",
            "summary": "",
            "url": "classes/mywishlist-mvc-views-UserView.html#property_secret"
        },                {
            "fqsen": "\\mywishlist\\Validator",
            "name": "Validator",
            "summary": "Class\u0020Validator\nValidates\u0020data",
            "url": "classes/mywishlist-Validator.html"
        },                {
            "fqsen": "\\mywishlist\\Validator\u003A\u003AvalidateFile\u0028\u0029",
            "name": "validateFile",
            "summary": "Validate\u0020a\u0020file",
            "url": "classes/mywishlist-Validator.html#method_validateFile"
        },                {
            "fqsen": "\\mywishlist\\Validator\u003A\u003AvalidateStrings\u0028\u0029",
            "name": "validateStrings",
            "summary": "Validate\u0020some\u0020strings",
            "url": "classes/mywishlist-Validator.html#method_validateStrings"
        },                {
            "fqsen": "\\mywishlist\\Validator\u003A\u003AvalidatePassword\u0028\u0029",
            "name": "validatePassword",
            "summary": "Validate\u0020a\u0020password",
            "url": "classes/mywishlist-Validator.html#method_validatePassword"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\mywishlist\\db",
            "name": "db",
            "summary": "",
            "url": "namespaces/mywishlist-db.html"
        },                {
            "fqsen": "\\mywishlist\\exceptions",
            "name": "exceptions",
            "summary": "",
            "url": "namespaces/mywishlist-exceptions.html"
        },                {
            "fqsen": "\\mywishlist",
            "name": "mywishlist",
            "summary": "",
            "url": "namespaces/mywishlist.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\controllers",
            "name": "controllers",
            "summary": "",
            "url": "namespaces/mywishlist-mvc-controllers.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\models",
            "name": "models",
            "summary": "",
            "url": "namespaces/mywishlist-mvc-models.html"
        },                {
            "fqsen": "\\mywishlist\\mvc",
            "name": "mvc",
            "summary": "",
            "url": "namespaces/mywishlist-mvc.html"
        },                {
            "fqsen": "\\mywishlist\\mvc\\views",
            "name": "views",
            "summary": "",
            "url": "namespaces/mywishlist-mvc-views.html"
        }            ]
);
